t = int(input("Digite a casa da tabuada:\n >>> "))
print(f"|Casa do >{t:0>3}<|\n|{'='*13}|")
print(f'| {t} x  1 = {t*1:>3}|')
print(f'| {t} x  2 = {t*2:>3}|')
print(f'| {t} x  3 = {t*3:>3}|')
print(f'| {t} x  4 = {t*4:>3}|')
print(f'| {t} x  5 = {t*5:>3}|')
print(f'| {t} x  6 = {t*6:>3}|')
print(f'| {t} x  7 = {t*7:>3}|')
print(f'| {t} x  8 = {t*8:>3}|')
print(f'| {t} x  9 = {t*9:>3}|')
print(f'| {t} x 10 = {t*10:>3}|')

